FROM python:3.9.8
WORKDIR /server_simulator
COPY . .
# RUN pip install -r requirements.txt
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
# CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "app:app"]
# CMD ./run_app.sh
CMD ["python", "server_simulator.py"]